package ReverseModule;


/**
* ReverseModule/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ReverseModule.idl
* Wednesday, 7 May, 2025 1:29:06 AM IST
*/

public interface ReverseOperations 
{
  String reverse_string (String name);
} // interface ReverseOperations
